### ISSUE TITLE
Support carbon 2.0

### ISSUE THREAD

**Issue by eberkund** [teamtnt/php-stripe-webhook-tester#11]
Will you support Carbon 2.0? I am having difficulties installing this package because of composer version conflicts.

**Comment by pierrocknroll** [comment]
This package will be incompatible with Cashier 10 :(

**Comment by eberkund** [comment]
I don't think Carbon is even used anywhere, I think that dependency can be removed altogether actually

**Comment by nticaric** [comment]
The latest merge fixes that thanks to @eberkund

**Comment by eberkund** [comment]
Thanks for merging, can you push the update to packagist?
