### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by jesseschutt** [teamtnt/php-stripe-webhook-tester#4]
Hey Guys - Wondering what it would take to get this package running on Guzzle 6, since that's what Laravel 5.2 is currently loading by default. Thanks!

**Comment by nticaric** [comment]
I think it shouldn't be much of a problem, will do it over the weekend

**Comment by jesseschutt** [comment]
Thank you! It also appears the stripe stubs are a bit out of date as well. I'll see if I can update them.

**Comment by nticaric** [comment]
Did the upgrade a little bit sooner, it was pretty simple :) Check out version 1.1

**Comment by jesseschutt** [comment]
Thank you! Much appreciated
