### ISSUE TITLE
Stripe API version

### ISSUE THREAD

**Issue by nikolaynesov** [teamtnt/php-stripe-webhook-tester#7]
Why does the package use '2014-09-08' (from README)?
If I change the version to something more recent then 2015-04-07. it fails with:
`TeamTNT\Stripe\InvalidEventException: Event does not exist in version `
triggering the event 'charge.succeeded'.
Can I use '2016-10-19' with 'charge.succeeded' event?

**Comment by nticaric** [comment]
Here's the list of versions that are available

https://github.com/teamtnt/php-stripe-webhook-tester/tree/master/src/webhooks

Feel free to add some new versions.

**Comment by pierrocknroll** [comment]
Why the default version is not the last, but the first ?!
